# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 003d5e3ab8962cf9d2775e1b90472b005984803c3354e9f46e0129ab4fefcc738fcabf5c5747807862ca629b350f79b6de2431405696aff1e8c7ecde5dc003f5

test:
  secret_key_base: 1204da8298da0e2e1b1f7df9aa135d6469201104610d87d02e444f6fe20f878f4f89439d49b710eb8317e3007a66d33ae43c98f6e5a0cb21dfa8b6b2c7e0c307

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
